# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Account_Project1\Account\Account.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 634)
        MainWindow.setStyleSheet("background-color: rgb(213, 213, 160);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 111, 21))
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.txtAccountname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAccountname.setGeometry(QtCore.QRect(150, 60, 341, 31))
        self.txtAccountname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtAccountname.setObjectName("txtAccountname")
        self.btnupdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnupdate.setGeometry(QtCore.QRect(290, 110, 61, 28))
        self.btnupdate.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnupdate.setObjectName("btnupdate")
        self.btnnew = QtWidgets.QPushButton(self.centralwidget)
        self.btnnew.setGeometry(QtCore.QRect(150, 110, 61, 28))
        self.btnnew.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnnew.setObjectName("btnnew")
        self.btndelete = QtWidgets.QPushButton(self.centralwidget)
        self.btndelete.setGeometry(QtCore.QRect(360, 110, 61, 28))
        self.btndelete.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btndelete.setObjectName("btndelete")
        self.btnsave = QtWidgets.QPushButton(self.centralwidget)
        self.btnsave.setGeometry(QtCore.QRect(220, 110, 61, 28))
        self.btnsave.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnsave.setObjectName("btnsave")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 110, 61, 28))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 160, 581, 461))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.cmbSelectgroup = QtWidgets.QComboBox(self.centralwidget)
        self.cmbSelectgroup.setGeometry(QtCore.QRect(150, 10, 341, 31))
        self.cmbSelectgroup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbSelectgroup.setObjectName("cmbSelectgroup")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "select Group"))
        self.label_2.setText(_translate("MainWindow", "Account Name"))
        self.btnupdate.setText(_translate("MainWindow", "Update"))
        self.btnnew.setText(_translate("MainWindow", "New"))
        self.btndelete.setText(_translate("MainWindow", "Delete"))
        self.btnsave.setText(_translate("MainWindow", "Save"))
        self.pushButton_5.setText(_translate("MainWindow", "Close"))
