# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Account_Project1\Group\Group.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 604)
        MainWindow.setStyleSheet("background-color: rgb(134, 255, 175);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 100, 16))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txtGroupname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtGroupname.setGeometry(QtCore.QRect(130, 20, 341, 31))
        self.txtGroupname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtGroupname.setObjectName("txtGroupname")
        self.btnnew = QtWidgets.QPushButton(self.centralwidget)
        self.btnnew.setGeometry(QtCore.QRect(130, 70, 61, 28))
        self.btnnew.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnnew.setObjectName("btnnew")
        self.btnsave = QtWidgets.QPushButton(self.centralwidget)
        self.btnsave.setGeometry(QtCore.QRect(200, 70, 61, 28))
        self.btnsave.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnsave.setObjectName("btnsave")
        self.btnupdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnupdate.setGeometry(QtCore.QRect(270, 70, 61, 28))
        self.btnupdate.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnupdate.setObjectName("btnupdate")
        self.btndelete = QtWidgets.QPushButton(self.centralwidget)
        self.btndelete.setGeometry(QtCore.QRect(340, 70, 61, 28))
        self.btndelete.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btndelete.setObjectName("btndelete")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 70, 61, 28))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 120, 511, 461))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_5.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Group Name"))
        self.btnnew.setText(_translate("MainWindow", "New"))
        self.btnsave.setText(_translate("MainWindow", "Save"))
        self.btnupdate.setText(_translate("MainWindow", "Update"))
        self.btndelete.setText(_translate("MainWindow", "Delete"))
        self.pushButton_5.setText(_translate("MainWindow", "Close"))
