# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Account_Project1\Transaction\Transaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 733)
        MainWindow.setStyleSheet("background-color: rgb(94, 190, 141);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmbSelectgroup = QtWidgets.QComboBox(self.centralwidget)
        self.cmbSelectgroup.setGeometry(QtCore.QRect(210, 20, 261, 31))
        self.cmbSelectgroup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbSelectgroup.setObjectName("cmbSelectgroup")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.cmbSelectAccount = QtWidgets.QComboBox(self.centralwidget)
        self.cmbSelectAccount.setGeometry(QtCore.QRect(210, 70, 261, 31))
        self.cmbSelectAccount.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbSelectAccount.setObjectName("cmbSelectAccount")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 131, 21))
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(210, 120, 261, 31))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 111, 21))
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 161, 31))
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.radReceived = QtWidgets.QRadioButton(self.centralwidget)
        self.radReceived.setGeometry(QtCore.QRect(209, 180, 111, 20))
        self.radReceived.setMinimumSize(QtCore.QSize(100, 0))
        self.radReceived.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.radReceived.setObjectName("radReceived")
        self.radPayment = QtWidgets.QRadioButton(self.centralwidget)
        self.radPayment.setGeometry(QtCore.QRect(360, 180, 111, 20))
        self.radPayment.setMinimumSize(QtCore.QSize(100, 0))
        self.radPayment.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.radPayment.setObjectName("radPayment")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 280, 451, 431))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 20, 111, 21))
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(550, 280, 441, 431))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.btndelete = QtWidgets.QPushButton(self.centralwidget)
        self.btndelete.setGeometry(QtCore.QRect(840, 150, 61, 28))
        self.btndelete.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btndelete.setObjectName("btndelete")
        self.btnupdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnupdate.setGeometry(QtCore.QRect(750, 150, 81, 28))
        self.btnupdate.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnupdate.setObjectName("btnupdate")
        self.btnnew = QtWidgets.QPushButton(self.centralwidget)
        self.btnnew.setGeometry(QtCore.QRect(610, 150, 61, 28))
        self.btnnew.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnnew.setObjectName("btnnew")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(910, 150, 61, 28))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.btnsave = QtWidgets.QPushButton(self.centralwidget)
        self.btnsave.setGeometry(QtCore.QRect(680, 150, 61, 28))
        self.btnsave.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnsave.setObjectName("btnsave")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 230, 141, 21))
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.txtAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAmount.setGeometry(QtCore.QRect(210, 230, 261, 31))
        self.txtAmount.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtAmount.setObjectName("txtAmount")
        self.textNote = QtWidgets.QTextEdit(self.centralwidget)
        self.textNote.setGeometry(QtCore.QRect(610, 20, 361, 111))
        self.textNote.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.textNote.setObjectName("textNote")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "select Group"))
        self.label_2.setText(_translate("MainWindow", "Select Account"))
        self.label_3.setText(_translate("MainWindow", "Date"))
        self.label_4.setText(_translate("MainWindow", "Transaction Type"))
        self.radReceived.setText(_translate("MainWindow", "Received"))
        self.radPayment.setText(_translate("MainWindow", "Payment"))
        self.label_5.setText(_translate("MainWindow", "Note"))
        self.btndelete.setText(_translate("MainWindow", "Delete"))
        self.btnupdate.setText(_translate("MainWindow", "Update"))
        self.btnnew.setText(_translate("MainWindow", "New"))
        self.pushButton_5.setText(_translate("MainWindow", "Close"))
        self.btnsave.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "Amount"))
