# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Account_Project1\Change_Password\Change_Password.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 203)
        MainWindow.setStyleSheet("background-color: rgb(255, 133, 239);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 111, 20))
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txtOldpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtOldpassword.setGeometry(QtCore.QRect(150, 30, 211, 31))
        self.txtOldpassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtOldpassword.setObjectName("txtOldpassword")
        self.txtNewpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNewpassword.setGeometry(QtCore.QRect(150, 90, 211, 31))
        self.txtNewpassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtNewpassword.setObjectName("txtNewpassword")
        self.btnChange = QtWidgets.QPushButton(self.centralwidget)
        self.btnChange.setGeometry(QtCore.QRect(150, 140, 93, 28))
        self.btnChange.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnChange.setObjectName("btnChange")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 140, 91, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Old Password"))
        self.label_2.setText(_translate("MainWindow", "New Password"))
        self.btnChange.setText(_translate("MainWindow", "Change"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
